# Name of your application. Used to uniquely configure containers.
service: service_id

# Name of the container image (use your-user/app-name on external registries).
image: service_id

# Deploy to these servers.
servers:
  web:
    - 192.168.0.1
  # job:
  #   hosts:
  #     - 192.168.0.1
  #   cmd: bin/jobs

# Enable SSL auto certification via Let's Encrypt and allow for multiple apps on a single web server.
# proxy:
#   ssl: true
#   host: app.example.com

# Where you keep your container images.
registry:
  server: localhost:5555

# Inject ENV variables into containers (secrets come from .kamal/secrets).
env:
  secret:
    - RAILS_MASTER_KEY
  clear:
    # Run the Solid Queue Supervisor inside the web server's Puma process to do jobs.
    SOLID_QUEUE_IN_PUMA: true

    # Onfido configuration
    # ONFIDO_API_TOKEN: set via secrets
    # ONFIDO_REGION: us

# Aliases are triggered with "bin/kamal <alias>".
aliases:
  console: app exec --interactive --reuse "bin/rails console"
  shell: app exec --interactive --reuse "bash"
  logs: app logs -f
  dbc: app exec --interactive --reuse "bin/rails dbconsole --include-password"

# Use a persistent storage volume for sqlite database files.
volumes:
  - "service_id_storage:/rails/storage"

# Bridge fingerprinted assets between versions.
asset_path: /rails/public/assets

# Configure the image builder.
builder:
  arch: amd64
